### PR TITLE
Enable azure_binding for sonarqube community edition

### PR DESCRIPTION
**Pull request by CyrineG**
This PR aims to solve https://github.com/jdamata/terraform-provider-sonarqube/issues/208

### CODE REVIEW

**Comment by jdamata** [comment]
Are we sure it's available on community? The check is dialing with unknown url on the API call

**Comment by CyrineG** [comment]
@jdamata A POST to the `api/alm_settings/set_azure_binding` endpoint works perfectly in my team's sonarqube instance. This is what I found about it in the [WebAPI docu ](https://next.sonarqube.com/sonarqube/web_api/api/alm_settings/set_azure_binding)
image 

Is there anything I can do to help you verify that it's available?

**Comment by jdamata** [comment]
Weird. Can you look into why the tests/checks are failing for community then? 

`2023-10-13T00:00:07.7681256Z 2023/10/12 23:55:50 [DEBUG] POST ***127.0.0.1:9000/api/projects/delete?project=testSqProjectKey
2023-10-13T00:00:07.7682283Z --- FAIL: TestAccSonarqubeAzureBindingName (3.36s)
2023-10-13T00:00:07.7683543Z     resource_sonarqube_azure_binding_test.go:49: Step 1/6 error: Error running apply: exit status 1
2023-10-13T00:00:07.7684390Z         
2023-10-13T00:00:07.7685169Z         Error: API returned an error: Unknown url : /api/alm_settings/set_azure_binding
2023-10-13T00:00:07.7686058Z         
2023-10-13T00:00:07.7686570Z           with sonarqube_azure_binding.gojswxscbf,
2023-10-13T00:00:07.7687685Z           on terraform_plugin_test.tf line 15, in resource "sonarqube_azure_binding" "gojswxscbf":
`

**Comment by CyrineG** [comment]
Hello! you were right, turns out that in addition to the community edition we were using the [sonarqube-community-branch-plugin ](https://github.com/mc1arke/sonarqube-community-branch-plugin) which made a ton of stuff not available to the community edition, available. Sorry about that! Will be closing the PR and related issue

**Pull request closed without merging**
